stages:
  - build java
  - build docker

build docker:
  stage: builddocker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build java:
  stage: buildjava
  image: gradle:6.5-jdk11
  script:
    - gradle bootJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 2 hours

